const $ = (s) => document.querySelector(s);
const today = new Date().toISOString().slice(0, 10);
const read = (key, fallback) => JSON.parse(localStorage.getItem(key) || JSON.stringify(fallback));
let tickets = read('soporte-ti-tickets', []);
let projects = read('soporte-ti-projects', []);
const save = () => { localStorage.setItem('soporte-ti-tickets', JSON.stringify(tickets)); localStorage.setItem('soporte-ti-projects', JSON.stringify(projects)); };
const fmt = (date) => date ? new Intl.DateTimeFormat('es-MX', { day:'2-digit', month:'short', year:'numeric' }).format(new Date(`${date}T12:00:00`)) : 'Sin fecha';
const code = (n) => `TI-${String(n).padStart(4, '0')}`;
const className = (value) => value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s/g,'-');

function renderStats() { const active = tickets.filter(x => x.status !== 'Resuelto'); const resolved = tickets.filter(x => x.status === 'Resuelto'); const inProgress = projects.filter(x => x.status !== 'Completado'); $('#stats').innerHTML = [['Tickets activos', active.length], ['Resueltos', resolved.length], ['Proyectos en curso', inProgress.length], ['Total actividades', tickets.length + projects.length]].map(([a,b]) => `<article class="stat"><p>${a}</p><strong>${b}</strong></article>`).join(''); }
function renderDashboard() { const recent = [...tickets].sort((a,b) => b.date.localeCompare(a.date)).slice(0,5); $('#recent-list').innerHTML = recent.length ? recent.map(x => `<div class="activity-row"><span class="ticket-icon">#</span><div><b>${escapeHtml(x.subject)}</b><small>${escapeHtml(x.requester)} · ${fmt(x.date)}</small></div><span class="badge status-${className(x.status)}">${x.status}</span></div>`).join('') : '<p class="empty">Aún no hay tickets registrados.</p>'; const statuses = ['Abierto','En proceso','En espera','Resuelto']; const total = tickets.length || 1; $('#status-summary').innerHTML = statuses.map(s => { const n = tickets.filter(x=>x.status===s).length; return `<div class="status-row"><span>${s}</span><div class="bar"><i style="width:${n/total*100}%"></i></div><b>${n}</b></div>`; }).join(''); }
function renderTickets() { const search = $('#ticket-search').value.toLowerCase(); const status = $('#ticket-status-filter').value; const list = tickets.filter(x => (!status || x.status === status) && `${x.subject} ${x.requester} ${x.area} ${code(x.number)}`.toLowerCase().includes(search)).sort((a,b)=>b.date.localeCompare(a.date)); $('#tickets-table').innerHTML = list.length ? list.map(x => `<tr data-id="${x.id}"><td><b>${code(x.number)}</b></td><td>${escapeHtml(x.subject)}</td><td>${escapeHtml(x.requester)}<small>${x.area ? `<br>${escapeHtml(x.area)}`:''}</small></td><td class="priority-${className(x.priority)}">${x.priority}</td><td><span class="badge status-${className(x.status)}">${x.status}</span></td><td>${fmt(x.date)}</td></tr>`).join('') : '<tr><td colspan="6" class="empty">No hay tickets que coincidan con la búsqueda.</td></tr>'; document.querySelectorAll('tr[data-id]').forEach(el=>el.onclick=()=>openTicket(tickets.find(x=>x.id===el.dataset.id))); }
function renderProjects() { $('#projects-grid').innerHTML = projects.length ? projects.map(x => `<article class="project-card" data-id="${x.id}"><div class="panel-heading"><h2>${escapeHtml(x.name)}</h2><span class="badge status-${className(x.status)}">${x.status}</span></div><p class="project-meta">${x.type} · ${x.owner || 'Sin responsable'}</p><p>${escapeHtml(x.update || 'Sin avance registrado.')}</p><div class="project-footer"><div class="progress"><i style="width:${x.progress}%"></i></div><b>${x.progress}%</b></div></article>`).join('') : '<p class="empty">Aún no hay proyectos registrados.</p>'; document.querySelectorAll('.project-card[data-id]').forEach(el=>el.onclick=()=>openProject(projects.find(x=>x.id===el.dataset.id))); }
function renderReport() { const from=$('#report-from').value, to=$('#report-to').value; const filtered=tickets.filter(x=>(!from||x.date>=from)&&(!to||x.date<=to)); const resolved=filtered.filter(x=>x.status==='Resuelto').length; $('#report-preview').innerHTML=`<b>${filtered.length}</b> tickets registrados${from||to ? ' en el periodo seleccionado':''}; <b>${resolved}</b> resueltos y <b>${projects.filter(x=>x.status!=='Completado').length}</b> proyectos activos.<br><br>El archivo incluye los tickets del periodo y el estado actual de todos los proyectos.`; }
function render() { renderStats(); renderDashboard(); renderTickets(); renderProjects(); renderReport(); }
function openTicket(item) { const f=$('#ticket-form'); f.reset(); $('#ticket-id').value=item?.id||''; $('#ticket-dialog-title').textContent=item?'Editar ticket':'Nuevo ticket'; $('#ticket-date').value=item?.date||today; ['subject','requester','area','priority','status','notes'].forEach(k=> $(`#ticket-${k}`).value=item?.[k]|| (k==='priority'?'Media':k==='status'?'Abierto':'')); $('#ticket-dialog').showModal(); }
function openProject(item) { const f=$('#project-form'); f.reset(); $('#project-id').value=item?.id||''; ['name','type','owner','progress','status','date','update'].forEach(k=> $(`#project-${k}`).value=item?.[k] ?? (k==='type'?'Base de datos':k==='progress'?0:k==='status'?'Planeación':'')); $('#project-dialog').showModal(); }
function escapeHtml(v='') { const d=document.createElement('div'); d.textContent=v; return d.innerHTML; }
function csv(rows) { return rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'); }
function download(name, content) { const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([`\ufeff${content}`],{type:'text/csv;charset=utf-8'})); a.download=name; a.click(); URL.revokeObjectURL(a.href); }

$('#today').textContent = new Intl.DateTimeFormat('es-MX',{weekday:'long', day:'numeric', month:'long'}).format(new Date());
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{ document.querySelectorAll('.nav-item,.view').forEach(x=>x.classList.remove('active')); b.classList.add('active'); $(`#${b.dataset.view}`).classList.add('active'); $('#view-title').textContent={dashboard:'Resumen de actividades',tickets:'Tickets de soporte',projects:'Avance de proyectos',reports:'Reportes'}[b.dataset.view]; $('#new-item').style.display=b.dataset.view==='projects'?'none':''; });
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>document.querySelector(`[data-view="${b.dataset.go}"]`).click());
$('#new-item').onclick=()=>openTicket(); $('#new-project').onclick=()=>openProject();
$('#ticket-form').addEventListener('submit',e=>{e.preventDefault(); const id=$('#ticket-id').value; const item={id:id||crypto.randomUUID(),number:id?tickets.find(x=>x.id===id).number:Math.max(0,...tickets.map(x=>x.number))+1,subject:$('#ticket-subject').value.trim(),requester:$('#ticket-requester').value.trim(),area:$('#ticket-area').value.trim(),priority:$('#ticket-priority').value,status:$('#ticket-status').value,date:$('#ticket-date').value,notes:$('#ticket-notes').value.trim()}; tickets=id?tickets.map(x=>x.id===id?item:x):[...tickets,item]; save(); $('#ticket-dialog').close(); render(); });
$('#project-form').addEventListener('submit',e=>{e.preventDefault(); const id=$('#project-id').value; const item={id:id||crypto.randomUUID(),name:$('#project-name').value.trim(),type:$('#project-type').value,owner:$('#project-owner').value.trim(),progress:Math.min(100,Math.max(0,Number($('#project-progress').value))),status:$('#project-status').value,date:$('#project-date').value,update:$('#project-update').value.trim()}; projects=id?projects.map(x=>x.id===id?item:x):[...projects,item]; save(); $('#project-dialog').close(); render(); });
$('#ticket-search').oninput=renderTickets; $('#ticket-status-filter').onchange=renderTickets; ['report-from','report-to'].forEach(id=>$( `#${id}`).addEventListener('change',renderReport));
$('#export-tickets').onclick=()=>download(`tickets-${today}.csv`,csv([['Folio','Asunto','Solicitante','Área','Prioridad','Estado','Fecha','Detalle'],...tickets.map(x=>[code(x.number),x.subject,x.requester,x.area,x.priority,x.status,x.date,x.notes])]));
$('#download-report').onclick=()=>{const from=$('#report-from').value,to=$('#report-to').value;const selected=tickets.filter(x=>(!from||x.date>=from)&&(!to||x.date<=to));const rows=[['REPORTE DE ACTIVIDADES TI'],['Periodo',`${from||'Inicio'} a ${to||'Hoy'}`],[],['TICKETS'],['Folio','Asunto','Solicitante','Área','Prioridad','Estado','Fecha','Detalle'],...selected.map(x=>[code(x.number),x.subject,x.requester,x.area,x.priority,x.status,x.date,x.notes]),[],['PROYECTOS'],['Proyecto','Tipo','Responsable','Avance','Estado','Fecha estimada','Último avance'],...projects.map(x=>[x.name,x.type,x.owner,`${x.progress}%`,x.status,x.date,x.update])];download(`reporte-soporte-ti-${today}.csv`,csv(rows));};
document.querySelectorAll('dialog [value="cancel"]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();button.closest('dialog').close();}));
const companies=['KINIK','SERVERINT','D3G','ASURATEC','AEGIS','ADMINISTRACIÓN','GERENCIA'];
function addCompanyField(companyId,beforeId){const input=$(beforeId);const label=document.createElement('label');label.innerHTML=`Empresa<select id="${companyId}" required><option value="">Selecciona una empresa</option>${companies.map(company=>`<option>${company}</option>`).join('')}</select>`;input.closest('label').before(label);}
addCompanyField('ticket-company','#ticket-area');
addCompanyField('project-company','#project-owner');
$('#ticket-form').addEventListener('submit',()=>{const item=$('#ticket-id').value?tickets.find(x=>x.id===$('#ticket-id').value):tickets.at(-1);if(item){item.company=$('#ticket-company').value;save();}});
$('#project-form').addEventListener('submit',()=>{const item=$('#project-id').value?projects.find(x=>x.id===$('#project-id').value):projects.at(-1);if(item){item.company=$('#project-company').value;save();}});
$('#export-tickets').addEventListener('click',event=>{event.stopImmediatePropagation();download(`tickets-${today}.csv`,csv([['Folio','Empresa','Asunto','Solicitante','Área','Prioridad','Estado','Fecha','Detalle'],...tickets.map(x=>[code(x.number),x.company||'',x.subject,x.requester,x.area,x.priority,x.status,x.date,x.notes])]));},{capture:true});
$('#download-report').addEventListener('click',event=>{event.stopImmediatePropagation();const from=$('#report-from').value,to=$('#report-to').value,selected=tickets.filter(x=>(!from||x.date>=from)&&(!to||x.date<=to));const rows=[['REPORTE DE ACTIVIDADES TI'],['Periodo',`${from||'Inicio'} a ${to||'Hoy'}`],[],['TICKETS'],['Folio','Empresa','Asunto','Solicitante','Área','Prioridad','Estado','Fecha','Detalle'],...selected.map(x=>[code(x.number),x.company||'',x.subject,x.requester,x.area,x.priority,x.status,x.date,x.notes]),[],['PROYECTOS'],['Proyecto','Empresa','Tipo','Responsable','Avance','Estado','Fecha estimada','Último avance'],...projects.map(x=>[x.name,x.company||'',x.type,x.owner,`${x.progress}%`,x.status,x.date,x.update])];download(`reporte-soporte-ti-${today}.csv`,csv(rows));},{capture:true});
render();
